log_file: ./logs/step_gap_ntlink.log
params:
  THREADS: 1
  NTLINK_BIN: /ibex/project/c2293/najdi_t2t_project/WP1_genome_assembly_qc/code/tools/miniconda3/envs/ntlink/bin/ntLink
  ASM_IN: /path/to/asm_in
  ONT_FASTQ: /path/to/ont_fastq
  WORK_DIR: /path/to/work_dir
  TAG: sample_asm
  POLISHER: racon
  FINAL_OUT: /path/to/final_out
